# For main branch releases
branches:
  - name: 'main'
  - name: 'dev'
    prerelease: 'beta'
    tagFormat: '${version}'
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/github'
  - '@semantic-release/git'
preset: 'angular'
tagFormat: 'v${version}'
