plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "semantic-release-yarn"
    - npmPublish: false
  - - "semantic-release-cargo"
    - publish: false
  - "@semantic-release/github"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: dev
    prerelease: '${name.replace(/^dev\//g, "dev-")}'
  - name: feature/*
    prerelease: '${name.replace(/^feature\//g, "feature-")}'
  - name: hotfix/*
    prerelease: '${name.replace(/^hotfix\//g, "hotfix-")}'
