plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "@semantic-release/git"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: dev
    prerelease: true
  - name: feature/*
    prerelease: '${name.replace(/^feature\//g, "feature-")}'
  - name: hotfix/*
    prerelease: '${name.replace(/^hotfix\//g, "hotfix-")}'

preset: 'angular'
tagFormat: 'v${version}-beta'
