branches: ['dev']
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/github'
  - '@semantic-release/git'
preset: 'angular'
tagFormat: 'v${version}-beta'
prerelease: 'beta'